import type { LifestyleKey, SecondarySkillEntry, SecondarySkillsByClass, SecondarySkillsByWorld } from './types';

export const SECONDARY_SKILL_DEFAULT_CLASS = 'default';
export const SECONDARY_SKILL_TWO = 'Roll for two skills';

type Band = [weight: number, skill: string, lifestyle: LifestyleKey];

export const skillTable = (bands: Band[]): SecondarySkillEntry[] => {
  let next = 1;
  const rows = bands.map(([weight, skill, lifestyle]) => {
    const min = next;
    const max = next + weight - 1;
    next = max + 1;
    return { min, max, skill, lifestyle };
  });
  if (next !== 101) {
    throw new Error(`Profession table must cover 1-100, got 1-${next - 1}`);
  }
  return rows;
};

export const resolveSecondarySkillTable = (
  tables: SecondarySkillsByWorld,
  theme: string,
  className: string,
): SecondarySkillEntry[] => {
  const world = tables[theme];
  const generic = tables.ose;
  return (
    world?.[className]
    || world?.[SECONDARY_SKILL_DEFAULT_CLASS]
    || generic?.[className]
    || generic?.[SECONDARY_SKILL_DEFAULT_CLASS]
    || []
  );
};

export const mergeSecondarySkillWorlds = (
  base: SecondarySkillsByWorld,
  overlay: SecondarySkillsByWorld,
): SecondarySkillsByWorld => {
  const next: SecondarySkillsByWorld = {};
  for (const [world, byClass] of Object.entries(base)) {
    next[world] = { ...byClass };
  }
  for (const [world, byClass] of Object.entries(overlay)) {
    next[world] = { ...(next[world] || {}), ...byClass };
  }
  return next;
};

export const lifestyleForSkill = (
  table: SecondarySkillEntry[],
  skillName: string,
): LifestyleKey => table.find((row) => row.skill === skillName)?.lifestyle ?? 'Modest';

const oseDefault: SecondarySkillEntry[] = [
  { min: 1, max: 3, skill: 'Animal trainer', lifestyle: 'Modest' },
  { min: 4, max: 5, skill: 'Armourer', lifestyle: 'Comfortable' },
  { min: 6, max: 9, skill: 'Baker', lifestyle: 'Modest' },
  { min: 10, max: 12, skill: 'Blacksmith', lifestyle: 'Modest' },
  { min: 13, max: 13, skill: 'Bookbinder', lifestyle: 'Comfortable' },
  { min: 14, max: 16, skill: 'Bowyer / fletcher', lifestyle: 'Modest' },
  { min: 17, max: 20, skill: 'Brewer', lifestyle: 'Modest' },
  { min: 21, max: 23, skill: 'Butcher', lifestyle: 'Modest' },
  { min: 24, max: 26, skill: 'Carpenter', lifestyle: 'Modest' },
  { min: 27, max: 28, skill: 'Chandler', lifestyle: 'Modest' },
  { min: 29, max: 33, skill: 'Cooper', lifestyle: 'Modest' },
  { min: 34, max: 35, skill: 'Coppersmith', lifestyle: 'Comfortable' },
  { min: 36, max: 46, skill: 'Farmer', lifestyle: 'Poor' },
  { min: 47, max: 50, skill: 'Fisher', lifestyle: 'Poor' },
  { min: 51, max: 54, skill: 'Furrier', lifestyle: 'Modest' },
  { min: 55, max: 55, skill: 'Glassblower', lifestyle: 'Wealthy' },
  { min: 56, max: 59, skill: 'Huntsman', lifestyle: 'Modest' },
  { min: 60, max: 62, skill: 'Lapidary / jeweller', lifestyle: 'Wealthy' },
  { min: 63, max: 66, skill: 'Lorimer', lifestyle: 'Comfortable' },
  { min: 67, max: 67, skill: 'Mapmaker', lifestyle: 'Comfortable' },
  { min: 68, max: 69, skill: 'Mason', lifestyle: 'Modest' },
  { min: 70, max: 73, skill: 'Miner', lifestyle: 'Poor' },
  { min: 74, max: 76, skill: 'Potter', lifestyle: 'Modest' },
  { min: 77, max: 78, skill: 'Roper', lifestyle: 'Poor' },
  { min: 79, max: 81, skill: 'Seafarer', lifestyle: 'Modest' },
  { min: 82, max: 84, skill: 'Shipwright', lifestyle: 'Comfortable' },
  { min: 85, max: 87, skill: 'Tailor', lifestyle: 'Modest' },
  { min: 88, max: 90, skill: 'Tanner', lifestyle: 'Poor' },
  { min: 91, max: 93, skill: 'Thatcher / roofer', lifestyle: 'Poor' },
  { min: 94, max: 96, skill: 'Woodcutter', lifestyle: 'Poor' },
  { min: 97, max: 98, skill: 'Vintner', lifestyle: 'Comfortable' },
  { min: 99, max: 100, skill: SECONDARY_SKILL_TWO, lifestyle: 'Modest' },
];

const oseByClass: SecondarySkillsByClass = {
  [SECONDARY_SKILL_DEFAULT_CLASS]: oseDefault,
  Fighter: skillTable([
    [12, 'Farmer', 'Poor'],
    [10, 'Village levy', 'Poor'],
    [10, 'Garrison soldier', 'Modest'],
    [8, 'Huntsman', 'Modest'],
    [8, 'Woodcutter', 'Poor'],
    [6, 'Armourer', 'Comfortable'],
    [6, 'Blacksmith', 'Modest'],
    [6, 'Miner', 'Poor'],
    [5, 'Animal trainer', 'Modest'],
    [5, 'Bowyer / fletcher', 'Modest'],
    [5, 'Mason', 'Modest'],
    [4, 'Seafarer', 'Modest'],
    [4, 'Fisher', 'Poor'],
    [4, 'Butcher', 'Modest'],
    [5, 'Caravan guard', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Cleric: skillTable([
    [12, 'Temple sexton', 'Poor'],
    [10, 'Scribe', 'Modest'],
    [8, 'Hospitaler', 'Modest'],
    [8, 'Chandler', 'Modest'],
    [8, 'Bookbinder', 'Comfortable'],
    [7, 'Herbalist', 'Modest'],
    [7, 'Miller', 'Modest'],
    [6, 'Farmer', 'Poor'],
    [6, 'Beekeeper', 'Modest'],
    [5, 'Choir singer', 'Poor'],
    [5, 'Tutor', 'Comfortable'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Potter', 'Modest'],
    [6, 'Itinerant preacher', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  'Magic-User': skillTable([
    [12, 'Scribe', 'Modest'],
    [10, 'Bookbinder', 'Comfortable'],
    [10, 'Tutor', 'Comfortable'],
    [8, 'Apothecary apprentice', 'Comfortable'],
    [8, 'Mapmaker', 'Comfortable'],
    [8, 'Glassblower', 'Wealthy'],
    [7, 'Papermaker', 'Modest'],
    [6, 'Chandler', 'Modest'],
    [6, 'Jeweller', 'Wealthy'],
    [5, 'Translator', 'Comfortable'],
    [5, 'Astrologer\'s boy', 'Modest'],
    [5, 'Herbalist', 'Modest'],
    [4, 'Potter', 'Modest'],
    [4, 'Farmer', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Thief: skillTable([
    [10, 'Porter', 'Poor'],
    [8, 'Rat-catcher', 'Squalid'],
    [8, 'Tanner', 'Poor'],
    [8, 'Seafarer', 'Modest'],
    [7, 'Tinker', 'Poor'],
    [7, 'Cutpurse\'s lookout', 'Squalid'],
    [6, 'Inn servant', 'Poor'],
    [6, 'Roper', 'Poor'],
    [6, 'Fisher', 'Poor'],
    [6, 'Locksmith apprentice', 'Modest'],
    [5, 'Actor / mummer', 'Poor'],
    [5, 'Chandler', 'Modest'],
    [5, 'Tailor', 'Modest'],
    [5, 'Dock worker', 'Squalid'],
    [8, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Dwarf: skillTable([
    [18, 'Miner', 'Poor'],
    [12, 'Mason', 'Modest'],
    [12, 'Blacksmith', 'Modest'],
    [10, 'Armourer', 'Comfortable'],
    [8, 'Coppersmith', 'Comfortable'],
    [8, 'Jeweller', 'Wealthy'],
    [6, 'Cooper', 'Modest'],
    [6, 'Brewer', 'Modest'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Farmer', 'Poor'],
    [4, 'Chandler', 'Modest'],
    [4, 'Potter', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Elf: skillTable([
    [14, 'Huntsman', 'Modest'],
    [12, 'Bowyer / fletcher', 'Modest'],
    [12, 'Woodcutter', 'Poor'],
    [8, 'Herbalist', 'Modest'],
    [8, 'Animal trainer', 'Modest'],
    [7, 'Furrier', 'Modest'],
    [6, 'Carpenter', 'Modest'],
    [6, 'Musician', 'Poor'],
    [5, 'Beekeeper', 'Modest'],
    [5, 'Potter', 'Modest'],
    [7, 'Farmer', 'Poor'],
    [4, 'Mapmaker', 'Comfortable'],
    [4, 'Vintner', 'Comfortable'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Halfling: skillTable([
    [22, 'Farmer', 'Poor'],
    [10, 'Baker', 'Modest'],
    [10, 'Brewer', 'Modest'],
    [8, 'Cook', 'Modest'],
    [8, 'Gardener', 'Poor'],
    [6, 'Miller', 'Modest'],
    [6, 'Potter', 'Modest'],
    [6, 'Tailor', 'Modest'],
    [5, 'Inn servant', 'Poor'],
    [5, 'Herbalist', 'Modest'],
    [4, 'Carpenter', 'Modest'],
    [4, 'Fisher', 'Poor'],
    [4, 'Beekeeper', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Gnome: skillTable([
    [14, 'Tinker', 'Modest'],
    [12, 'Jeweller', 'Wealthy'],
    [10, 'Potter', 'Modest'],
    [8, 'Glassblower', 'Wealthy'],
    [8, 'Clock-maker', 'Comfortable'],
    [8, 'Miner', 'Poor'],
    [6, 'Coppersmith', 'Comfortable'],
    [6, 'Bookbinder', 'Comfortable'],
    [6, 'Mapmaker', 'Comfortable'],
    [5, 'Chandler', 'Modest'],
    [5, 'Carpenter', 'Modest'],
    [6, 'Farmer', 'Poor'],
    [4, 'Brewer', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Drow: skillTable([
    [12, 'Poisoner\'s apprentice', 'Comfortable'],
    [10, 'Silk-weaver', 'Comfortable'],
    [10, 'Jeweller', 'Wealthy'],
    [8, 'Scribe', 'Modest'],
    [8, 'Animal trainer', 'Modest'],
    [8, 'Miner', 'Poor'],
    [7, 'Herbalist', 'Modest'],
    [6, 'Glassblower', 'Wealthy'],
    [6, 'Musician', 'Poor'],
    [5, 'Mapmaker', 'Comfortable'],
    [5, 'Tailor', 'Modest'],
    [5, 'Chandler', 'Modest'],
    [4, 'Porter', 'Poor'],
    [4, 'Tanner', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Duergar: skillTable([
    [16, 'Miner', 'Poor'],
    [12, 'Blacksmith', 'Modest'],
    [10, 'Armourer', 'Comfortable'],
    [8, 'Mason', 'Modest'],
    [8, 'Overburdened porter', 'Squalid'],
    [7, 'Coppersmith', 'Comfortable'],
    [6, 'Tanner', 'Poor'],
    [6, 'Brewer', 'Modest'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Chandler', 'Modest'],
    [5, 'Scribe', 'Modest'],
    [4, 'Rat-catcher', 'Squalid'],
    [6, 'Farmer', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Svirfneblin: skillTable([
    [14, 'Gem-cutter', 'Wealthy'],
    [12, 'Miner', 'Poor'],
    [10, 'Mason', 'Modest'],
    [8, 'Tinker', 'Modest'],
    [8, 'Potter', 'Modest'],
    [7, 'Mapmaker', 'Comfortable'],
    [6, 'Glassblower', 'Wealthy'],
    [6, 'Scribe', 'Modest'],
    [6, 'Fungus-farmer', 'Poor'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Chandler', 'Modest'],
    [5, 'Jeweller', 'Wealthy'],
    [6, 'Porter', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  'Half-Elf': skillTable([
    [12, 'Huntsman', 'Modest'],
    [14, 'Farmer', 'Poor'],
    [8, 'Scribe', 'Modest'],
    [8, 'Woodcutter', 'Poor'],
    [8, 'Bowyer / fletcher', 'Modest'],
    [7, 'Herbalist', 'Modest'],
    [6, 'Carpenter', 'Modest'],
    [6, 'Musician', 'Poor'],
    [6, 'Translator', 'Comfortable'],
    [5, 'Inn servant', 'Poor'],
    [5, 'Tailor', 'Modest'],
    [5, 'Fisher', 'Poor'],
    [4, 'Mapmaker', 'Comfortable'],
    [4, 'Seafarer', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  'Half-Orc': skillTable([
    [14, 'Laborer', 'Poor'],
    [12, 'Butcher', 'Modest'],
    [10, 'Garrison soldier', 'Modest'],
    [8, 'Miner', 'Poor'],
    [8, 'Tanner', 'Poor'],
    [7, 'Woodcutter', 'Poor'],
    [6, 'Porter', 'Poor'],
    [6, 'Dock worker', 'Squalid'],
    [5, 'Blacksmith', 'Modest'],
    [5, 'Caravan guard', 'Modest'],
    [5, 'Rat-catcher', 'Squalid'],
    [4, 'Fisher', 'Poor'],
    [4, 'Farmer', 'Poor'],
    [4, 'Armourer', 'Comfortable'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Ranger: skillTable([
    [16, 'Huntsman', 'Modest'],
    [12, 'Trapper', 'Poor'],
    [10, 'Woodcutter', 'Poor'],
    [8, 'Guide', 'Modest'],
    [8, 'Furrier', 'Modest'],
    [7, 'Herbalist', 'Modest'],
    [6, 'Bowyer / fletcher', 'Modest'],
    [6, 'Animal trainer', 'Modest'],
    [5, 'Fisher', 'Poor'],
    [5, 'Farmer', 'Poor'],
    [4, 'Mapmaker', 'Comfortable'],
    [4, 'Carpenter', 'Modest'],
    [3, 'Beekeeper', 'Modest'],
    [4, 'Village levy', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Paladin: skillTable([
    [14, 'Temple guard', 'Modest'],
    [12, 'Squire', 'Comfortable'],
    [10, 'Hospitaler', 'Modest'],
    [8, 'Sexton', 'Poor'],
    [8, 'Farrier', 'Modest'],
    [7, 'Scribe', 'Modest'],
    [6, 'Armourer', 'Comfortable'],
    [6, 'Farmer', 'Poor'],
    [5, 'Tutor', 'Comfortable'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Animal trainer', 'Modest'],
    [4, 'Chandler', 'Modest'],
    [4, 'Miller', 'Modest'],
    [4, 'Garrison soldier', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Knight: skillTable([
    [16, 'Squire', 'Comfortable'],
    [12, 'Farrier', 'Modest'],
    [10, 'Herald', 'Comfortable'],
    [8, 'Armourer', 'Comfortable'],
    [8, 'Horse-trainer', 'Comfortable'],
    [7, 'Garrison soldier', 'Modest'],
    [6, 'Lorimer', 'Comfortable'],
    [6, 'Falconer', 'Wealthy'],
    [5, 'Scribe', 'Modest'],
    [5, 'Carpenter', 'Modest'],
    [4, 'Farmer', 'Poor'],
    [4, 'Blacksmith', 'Modest'],
    [3, 'Vintner', 'Comfortable'],
    [4, 'Huntsman', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Barbarian: skillTable([
    [14, 'Herder', 'Poor'],
    [12, 'Hunter', 'Poor'],
    [10, 'Raider', 'Poor'],
    [8, 'Woodcutter', 'Poor'],
    [8, 'Tanner', 'Poor'],
    [7, 'Fisher', 'Poor'],
    [6, 'Animal trainer', 'Modest'],
    [6, 'Boat-builder', 'Modest'],
    [5, 'Brewer', 'Modest'],
    [5, 'Potter', 'Modest'],
    [5, 'Storyteller', 'Poor'],
    [4, 'Miner', 'Poor'],
    [4, 'Carpenter', 'Modest'],
    [4, 'Farmer', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Druid: skillTable([
    [14, 'Herbalist', 'Modest'],
    [12, 'Beekeeper', 'Modest'],
    [10, 'Woodward', 'Modest'],
    [8, 'Farmer', 'Poor'],
    [8, 'Huntsman', 'Modest'],
    [7, 'Animal trainer', 'Modest'],
    [6, 'Miller', 'Modest'],
    [6, 'Potter', 'Modest'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Fisher', 'Poor'],
    [5, 'Tanner', 'Poor'],
    [4, 'Chandler', 'Modest'],
    [4, 'Storyteller', 'Poor'],
    [4, 'Gardener', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Bard: skillTable([
    [14, 'Tavern musician', 'Poor'],
    [12, 'Scribe', 'Modest'],
    [10, 'Storyteller', 'Poor'],
    [8, 'Actor / mummer', 'Poor'],
    [8, 'Tutor', 'Comfortable'],
    [7, 'Herald', 'Comfortable'],
    [6, 'Tailor', 'Modest'],
    [6, 'Inn servant', 'Poor'],
    [5, 'Bookbinder', 'Comfortable'],
    [5, 'Carpenter', 'Modest'],
    [5, 'Translator', 'Comfortable'],
    [4, 'Potter', 'Modest'],
    [4, 'Farmer', 'Poor'],
    [4, 'Seafarer', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Assassin: skillTable([
    [12, 'Apothecary apprentice', 'Comfortable'],
    [10, 'Tanner', 'Poor'],
    [8, 'Scribe', 'Modest'],
    [8, 'Rat-catcher', 'Squalid'],
    [8, 'Porter', 'Poor'],
    [7, 'Barber-surgeon', 'Modest'],
    [6, 'Locksmith apprentice', 'Modest'],
    [6, 'Inn servant', 'Poor'],
    [6, 'Chandler', 'Modest'],
    [5, 'Herbalist', 'Modest'],
    [5, 'Tailor', 'Modest'],
    [5, 'Seafarer', 'Modest'],
    [4, 'Glassblower', 'Wealthy'],
    [4, 'Farmer', 'Poor'],
    [6, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Acrobat: skillTable([
    [14, 'Tumbler', 'Poor'],
    [12, 'Rope-walker', 'Poor'],
    [10, 'Circus hand', 'Squalid'],
    [8, 'Roper', 'Poor'],
    [8, 'Actor / mummer', 'Poor'],
    [7, 'Carpenter', 'Modest'],
    [6, 'Tailor', 'Modest'],
    [6, 'Inn servant', 'Poor'],
    [5, 'Porter', 'Poor'],
    [5, 'Musician', 'Poor'],
    [5, 'Thatcher / roofer', 'Poor'],
    [4, 'Sail-maker', 'Modest'],
    [4, 'Farmer', 'Poor'],
    [4, 'Fisher', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Illusionist: skillTable([
    [12, 'Painter', 'Modest'],
    [10, 'Glassblower', 'Wealthy'],
    [10, 'Mummer', 'Poor'],
    [8, 'Scribe', 'Modest'],
    [8, 'Dyer', 'Modest'],
    [7, 'Tailor', 'Modest'],
    [6, 'Chandler', 'Modest'],
    [6, 'Jeweller', 'Wealthy'],
    [6, 'Bookbinder', 'Comfortable'],
    [5, 'Potter', 'Modest'],
    [5, 'Tutor', 'Comfortable'],
    [5, 'Papermaker', 'Modest'],
    [4, 'Carpenter', 'Modest'],
    [6, 'Farmer', 'Poor'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
  Sage: skillTable([
    [16, 'Scribe', 'Modest'],
    [12, 'Bookbinder', 'Comfortable'],
    [10, 'Tutor', 'Comfortable'],
    [8, 'Mapmaker', 'Comfortable'],
    [8, 'Translator', 'Comfortable'],
    [7, 'Librarian\'s clerk', 'Modest'],
    [6, 'Herbalist', 'Modest'],
    [6, 'Apothecary apprentice', 'Comfortable'],
    [5, 'Chandler', 'Modest'],
    [5, 'Papermaker', 'Modest'],
    [4, 'Glassblower', 'Wealthy'],
    [4, 'Jeweller', 'Wealthy'],
    [3, 'Farmer', 'Poor'],
    [4, 'Carpenter', 'Modest'],
    [2, SECONDARY_SKILL_TWO, 'Modest'],
  ]),
};

export const SECONDARY_SKILLS: SecondarySkillsByWorld = {
  ose: oseByClass,
};
