import type { Spell } from './types';

export const SPELLS: Spell[] = [
  // Cleric Spells
  { name: 'Cure Light Wounds', level: 1, description: 'Heals 1d6+1 hp.', class: 'Cleric' },
  { name: 'Detect Evil', level: 1, description: 'Reveals evil creatures or magic.', class: 'Cleric' },
  { name: 'Detect Magic', level: 1, description: 'Reveals magical auras.', class: 'Cleric' },
  { name: 'Light', level: 1, description: 'Creates light equal to torch/lantern.', class: 'Cleric' },
  { name: 'Protection from Evil', level: 1, description: '+1 AC/saves against evil creatures.', class: 'Cleric' },
  { name: 'Purify Food and Water', level: 1, description: 'Makes spoiled food/drink pure.', class: 'Cleric' },
  { name: 'Remove Fear', level: 1, description: 'Ends fear, grants save bonus.', class: 'Cleric' },
  { name: 'Resist Cold', level: 1, description: 'Grants resistance to cold.', class: 'Cleric' },
  { name: 'Bless', level: 2, description: 'Allies gain +1 attack, morale boost.', class: 'Cleric' },
  { name: 'Find Traps', level: 2, description: 'Reveals traps.', class: 'Cleric' },
  { name: 'Hold Person', level: 2, description: 'Paralyzes humanoids.', class: 'Cleric' },
  { name: 'Resist Fire', level: 2, description: 'Grants resistance to fire.', class: 'Cleric' },
  { name: 'Silence 15\' Radius', level: 2, description: 'Creates zone of silence.', class: 'Cleric' },
  { name: 'Snake Charm', level: 2, description: 'Charms snakes.', class: 'Cleric' },
  { name: 'Continual Light', level: 3, description: 'Creates permanent light.', class: 'Cleric' },
  { name: 'Cure Disease', level: 3, description: 'Removes disease.', class: 'Cleric' },
  { name: 'Locate Object', level: 3, description: 'Reveals direction of an object.', class: 'Cleric' },
  { name: 'Remove Curse', level: 3, description: 'Ends a curse.', class: 'Cleric' },
  { name: 'Speak with Dead', level: 3, description: 'Question a corpse.', class: 'Cleric' },
  { name: 'Create Water', level: 4, description: 'Creates water.', class: 'Cleric' },
  { name: 'Cure Serious Wounds', level: 4, description: 'Heals 2d6+2 hp.', class: 'Cleric' },
  { name: 'Neutralize Poison', level: 4, description: 'Ends poison.', class: 'Cleric' },
  { name: 'Protection from Evil 10\' Radius', level: 4, description: 'Protects group.', class: 'Cleric' },
  { name: 'Speak with Plants', level: 4, description: 'Communicate with plants.', class: 'Cleric' },
  { name: 'Commune', level: 5, description: 'Ask deity 3 questions.', class: 'Cleric' },
  { name: 'Create Food', level: 5, description: 'Creates food.', class: 'Cleric' },
  { name: 'Dispel Evil', level: 5, description: 'Banishes summoned/enchanted beings.', class: 'Cleric' },
  { name: 'Insect Plague', level: 5, description: 'Summons locust swarm.', class: 'Cleric' },
  { name: 'Quest', level: 5, description: 'Compels subject to task.', class: 'Cleric' },

  // Magic-User Spells
  { name: 'Charm Person', level: 1, description: 'Charms humanoid.', class: 'Magic-User' },
  { name: 'Detect Magic', level: 1, description: 'Reveals magic.', class: 'Magic-User' },
  { name: 'Floating Disc', level: 1, description: 'Creates levitating disc.', class: 'Magic-User' },
  { name: 'Hold Portal', level: 1, description: 'Holds door shut.', class: 'Magic-User' },
  { name: 'Light', level: 1, description: 'Creates light.', class: 'Magic-User' },
  { name: 'Magic Missile', level: 1, description: 'Unerring energy dart.', class: 'Magic-User' },
  { name: 'Protection from Evil', level: 1, description: '+1 AC/saves vs evil.', class: 'Magic-User' },
  { name: 'Read Languages', level: 1, description: 'Decipher texts.', class: 'Magic-User' },
  { name: 'Read Magic', level: 1, description: 'Decipher spell scrolls.', class: 'Magic-User' },
  { name: 'Shield', level: 1, description: '+2 AC front, blocks missiles.', class: 'Magic-User' },
  { name: 'Sleep', level: 1, description: 'Puts creatures to sleep.', class: 'Magic-User' },
  { name: 'Ventriloquism', level: 1, description: 'Project voice.', class: 'Magic-User' },
  { name: 'Continual Light', level: 2, description: 'Creates permanent light.', class: 'Magic-User' },
  { name: 'Detect Evil', level: 2, description: 'Reveals evil.', class: 'Magic-User' },
  { name: 'Detect Invisibility', level: 2, description: 'Reveals invisible things.', class: 'Magic-User' },
  { name: 'ESP', level: 2, description: 'Read thoughts.', class: 'Magic-User' },
  { name: 'Invisibility', level: 2, description: 'Target becomes invisible.', class: 'Magic-User' },
  { name: 'Knock', level: 2, description: 'Opens locks.', class: 'Magic-User' },
  { name: 'Levitate', level: 2, description: 'Rise and descend.', class: 'Magic-User' },
  { name: 'Locate Object', level: 2, description: 'Sense object’s direction.', class: 'Magic-User' },
  { name: 'Mirror Image', level: 2, description: 'Creates illusory doubles.', class: 'Magic-User' },
  { name: 'Phantasmal Force', level: 2, description: 'Creates illusion.', class: 'Magic-User' },
  { name: 'Web', level: 2, description: 'Creates sticky webs.', class: 'Magic-User' },
  { name: 'Clairvoyance', level: 3, description: 'See distant place.', class: 'Magic-User' },
  { name: 'Dispel Magic', level: 3, description: 'Ends magic.', class: 'Magic-User' },
  { name: 'Fireball', level: 3, description: 'Blast for 1d6/level damage.', class: 'Magic-User' },
  { name: 'Fly', level: 3, description: 'Grants flight.', class: 'Magic-User' },
  { name: 'Haste', level: 3, description: 'Doubles movement/attacks.', class: 'Magic-User' },
  { name: 'Hold Person', level: 3, description: 'Paralyzes humanoids.', class: 'Magic-User' },
  { name: 'Infravision', level: 3, description: 'Grants darkvision.', class: 'Magic-User' },
  { name: 'Invisibility 10\' Radius', level: 3, description: 'Grants group invisibility.', class: 'Magic-User' },
  { name: 'Lightning Bolt', level: 3, description: 'Bolt for 1d6/level damage.', class: 'Magic-User' },
  { name: 'Protection from Evil 10\' Radius', level: 3, description: 'Protects group.', class: 'Magic-User' },
  { name: 'Protection from Normal Missiles', level: 3, description: 'Immune to nonmagical missiles.', class: 'Magic-User' },
  { name: 'Water Breathing', level: 3, description: 'Breathe underwater.', class: 'Magic-User' },
  { name: 'Charm Monster', level: 4, description: 'Charms monster.', class: 'Magic-User' },
  { name: 'Confusion', level: 4, description: 'Targets act randomly.', class: 'Magic-User' },
  { name: 'Dimension Door', level: 4, description: 'Short teleport.', class: 'Magic-User' },
  { name: 'Growth of Plants', level: 4, description: 'Makes plants grow.', class: 'Magic-User' },
  { name: 'Hallucinatory Terrain', level: 4, description: 'Creates illusory terrain.', class: 'Magic-User' },
  { name: 'Ice Storm/Wall of Ice', level: 4, description: 'Blizzard or wall of ice.', class: 'Magic-User' },
  { name: 'Massmorph', level: 4, description: 'Hide group as trees.', class: 'Magic-User' },
  { name: 'Polymorph Other', level: 4, description: 'Transform another.', class: 'Magic-User' },
  { name: 'Polymorph Self', level: 4, description: 'Transform self.', class: 'Magic-User' },
  { name: 'Remove Curse', level: 4, description: 'Ends curse.', class: 'Magic-User' },
  { name: 'Wall of Fire', level: 4, description: 'Creates fire wall.', class: 'Magic-User' },
  { name: 'Wizard Eye', level: 4, description: 'Creates invisible scout eye.', class: 'Magic-User' },
  { name: 'Animate Dead', level: 5, description: 'Raises skeletons/zombies.', class: 'Magic-User' },
  { name: 'Cloudkill', level: 5, description: 'Deadly poison cloud.', class: 'Magic-User' },
  { name: 'Conjure Elemental', level: 5, description: 'Summons elemental.', class: 'Magic-User' },
  { name: 'Feeblemind', level: 5, description: 'Destroys caster’s mind.', class: 'Magic-User' },
  { name: 'Hold Monster', level: 5, description: 'Paralyzes monsters.', class: 'Magic-User' },
  { name: 'Magic Jar', level: 5, description: 'Possess another.', class: 'Magic-User' },
  { name: 'Passwall', level: 5, description: 'Opens passage in wall.', class: 'Magic-User' },
  { name: 'Telekinesis', level: 5, description: 'Move things mentally.', class: 'Magic-User' },
  { name: 'Teleport', level: 5, description: 'Long-distance teleport.', class: 'Magic-User' },
  { name: 'Wall of Stone', level: 5, description: 'Creates stone wall.', class: 'Magic-User' },

  // Druid Spells
  { name: 'Animal Friendship', level: 1, description: 'Enchants an animal into friendship.', class: 'Druid' },
  { name: 'Detect Danger', level: 1, description: 'Reveals nearby threats.', class: 'Druid' },
  { name: 'Entangle', level: 1, description: 'Plants restrain creatures in area.', class: 'Druid' },
  { name: 'Faerie Fire', level: 1, description: 'Outlines creatures, negates invisibility.', class: 'Druid' },
  { name: 'Invisibility to Animals', level: 1, description: 'Animals cannot perceive target.', class: 'Druid' },
  { name: 'Locate Plant or Animal', level: 1, description: 'Reveals direction of a specific plant or animal.', class: 'Druid' },
  { name: 'Predict Weather', level: 1, description: 'Forecasts local weather.', class: 'Druid' },
  { name: 'Speak with Animals', level: 1, description: 'Communicate with normal animals.', class: 'Druid' },
  { name: 'Barkskin', level: 2, description: 'Toughens skin, improving AC.', class: 'Druid' },
  { name: 'Create Water', level: 2, description: 'Creates drinkable water.', class: 'Druid' },
  { name: 'Cure Light Wounds', level: 2, description: 'Heals 1d6+1 hp. (Reversible: Cause Light Wounds)', class: 'Druid' },
  { name: 'Heat Metal', level: 2, description: 'Heats metal, damaging those who wear/carry it.', class: 'Druid' },
  { name: 'Obscuring Mist', level: 2, description: 'Creates fog that obscures vision.', class: 'Druid' },
  { name: 'Produce Flame', level: 2, description: 'Creates a flame in the caster’s hand, usable for attacks.', class: 'Druid' },
  { name: 'Slow Poison', level: 2, description: 'Delays effects of poison.', class: 'Druid' },
  { name: 'Warp Wood', level: 2, description: 'Bends or warps wooden objects.', class: 'Druid' },
  { name: 'Call Lightning', level: 3, description: 'Summons lightning bolts during storms.', class: 'Druid' },
  { name: 'Growth of Nature', level: 3, description: 'Causes plants to grow massively.', class: 'Druid' },
  { name: 'Hold Animal', level: 3, description: 'Paralyzes animals.', class: 'Druid' },
  { name: 'Protection from Poison', level: 3, description: 'Grants immunity to poison.', class: 'Druid' },
  { name: 'Tree Shape', level: 3, description: 'Caster takes the form of a tree.', class: 'Druid' },
  { name: 'Water Breathing', level: 3, description: 'Target can breathe underwater. (Reversible: Air Breathing)', class: 'Druid' },
  { name: 'Cure Serious Wounds', level: 4, description: 'Heals 2d6+2 hp. (Reversible: Cause Serious Wounds)', class: 'Druid' },
  { name: 'Dispel Magic', level: 4, description: 'Ends ongoing spells in an area.', class: 'Druid' },
  { name: 'Protection from Fire and Lightning', level: 4, description: 'Grants resistance to fire and lightning.', class: 'Druid' },
  { name: 'Speak with Plants', level: 4, description: 'Communicate with plants.', class: 'Druid' },
  { name: 'Summon Animals', level: 4, description: 'Summons animals to aid caster.', class: 'Druid' },
  { name: 'Temperature Control', level: 4, description: 'Raises or lowers local temperature.', class: 'Druid' },
  { name: 'Commune with Nature', level: 5, description: 'Gain knowledge of surrounding natural features.', class: 'Druid' },
  { name: 'Control Weather', level: 5, description: 'Changes local weather conditions.', class: 'Druid' },
  { name: 'Pass Plant', level: 5, description: 'Step into one tree and exit another.', class: 'Druid' },
  { name: 'Protection from Plants and Animals', level: 5, description: 'Wards against attacks from plants and animals.', class: 'Druid' },
  { name: 'Transmute Rock to Mud', level: 5, description: 'Turns rock into mud (Reversible: Mud to Rock).', class: 'Druid' },
  { name: 'Wall of Thorns', level: 5, description: 'Creates a barrier of thick, thorny brush.', class: 'Druid' },

  // Illusionist Spells
  { name: 'Auditory Illusion', level: 1, description: 'Creates illusory sounds.', class: 'Illusionist' },
  { name: 'Chromatic Orb', level: 1, description: 'Orb with random effects by caster level.', class: 'Illusionist' },
  { name: 'Colour Spray', level: 1, description: 'Stuns or blinds targets with flashing lights.', class: 'Illusionist' },
  { name: 'Dancing Lights', level: 1, description: 'Creates moving lights.', class: 'Illusionist' },
  { name: 'Detect Illusion', level: 1, description: 'Reveals illusions.', class: 'Illusionist' },
  { name: 'Glamour', level: 1, description: 'Changes appearance of the caster.', class: 'Illusionist' },
  { name: 'Hypnotism', level: 1, description: 'Fascinates or suggests action to a creature.', class: 'Illusionist' },
  { name: 'Light (Darkness)', level: 1, description: 'Creates light or darkness.', class: 'Illusionist' },
  { name: 'Phantasmal Force', level: 1, description: 'Creates an illusory object or creature.', class: 'Illusionist' },
  { name: 'Read Magic', level: 1, description: 'Read scrolls or inscriptions.', class: 'Illusionist' },
  { name: 'Spook', level: 1, description: 'Causes a target to flee in fear.', class: 'Illusionist' },
  { name: 'Wall of Fog', level: 1, description: 'Creates an obscuring fog wall.', class: 'Illusionist' },
  { name: 'Blindness/Deafness', level: 2, description: 'Permanently blinds or deafens a creature.', class: 'Illusionist' },
  { name: 'Blur', level: 2, description: 'Blurs caster’s outline, giving AC bonus.', class: 'Illusionist' },
  { name: 'Detect Magic', level: 2, description: 'Reveals magical auras.', class: 'Illusionist' },
  { name: 'False Aura', level: 2, description: 'Alters magical aura of an item.', class: 'Illusionist' },
  { name: 'Fascinate', level: 2, description: 'Captivates creatures with performance.', class: 'Illusionist' },
  { name: 'Hypnotic Pattern', level: 2, description: 'Pattern of lights holds creatures rapt.', class: 'Illusionist' },
  { name: 'Improved Phantasmal Force', level: 2, description: 'More realistic illusion than Phantasmal Force.', class: 'Illusionist' },
  { name: 'Invisibility', level: 2, description: 'Target becomes invisible until broken.', class: 'Illusionist' },
  { name: 'Magic Mouth', level: 2, description: 'Creates a triggered message.', class: 'Illusionist' },
  { name: 'Mirror Image', level: 2, description: 'Creates illusory duplicates of the caster.', class: 'Illusionist' },
  { name: 'Quasimorph', level: 2, description: 'Creates a distorted double of the caster.', class: 'Illusionist' },
  { name: 'Whispering Wind', level: 2, description: 'Carries a message on the wind.', class: 'Illusionist' },
  { name: 'Blacklight', level: 3, description: 'Creates magical darkness.', class: 'Illusionist' },
  { name: 'Dispel Illusion', level: 3, description: 'Ends an illusion effect.', class: 'Illusionist' },
  { name: 'Fear', level: 3, description: 'Causes creatures to flee.', class: 'Illusionist' },
  { name: 'Hallucinatory Terrain', level: 3, description: 'Changes appearance of terrain.', class: 'Illusionist' },
  { name: 'Invisibility 10\' Radius', level: 3, description: 'Grants invisibility to group in 10’ radius.', class: 'Illusionist' },
  { name: 'Nondetection', level: 3, description: 'Protects against divination and scrying.', class: 'Illusionist' },
  { name: 'Paralysation', level: 3, description: 'Illusory paralysis afflicts creatures.', class: 'Illusionist' },
  { name: 'Phantom Steed', level: 3, description: 'Summons an illusory steed.', class: 'Illusionist' },
  { name: 'Rope Trick', level: 3, description: 'Creates extra-dimensional space.', class: 'Illusionist' },
  { name: 'Spectral Force', level: 3, description: 'Illusion with sound, smell, and temperature.', class: 'Illusionist' },
  { name: 'Suggestion', level: 3, description: 'Implants a compelling suggestion.', class: 'Illusionist' },
  { name: 'Wraithform', level: 3, description: 'Caster becomes insubstantial.', class: 'Illusionist' },
  { name: 'Confusion', level: 4, description: 'Causes random actions in creatures.', class: 'Illusionist' },
  { name: 'Dispel Magic', level: 4, description: 'Ends ongoing spells in area.', class: 'Illusionist' },
  { name: 'Emotion', level: 4, description: 'Instills strong emotions in group.', class: 'Illusionist' },
  { name: 'Illusory Wall', level: 4, description: 'Creates convincing illusion of a wall.', class: 'Illusionist' },
  { name: 'Massmorph', level: 4, description: 'Conceals creatures as trees.', class: 'Illusionist' },
  { name: 'Minor Creation', level: 4, description: 'Creates small temporary objects.', class: 'Illusionist' },
  { name: 'Phantasmal Killer', level: 4, description: 'Illusory killer attacks and may slay target.', class: 'Illusionist' },
  { name: 'Rainbow Pattern', level: 4, description: 'Fascinates creatures with shifting lights.', class: 'Illusionist' },
  { name: 'Shadow Monsters', level: 4, description: 'Creates illusory monsters with partial reality.', class: 'Illusionist' },
  { name: 'Solid Fog', level: 4, description: 'Thick fog slows movement severely.', class: 'Illusionist' },
  { name: 'Chaos', level: 5, description: 'Creatures act randomly as confusion spreads.', class: 'Illusionist' },
  { name: 'Demi-Shadow Monsters', level: 5, description: 'Illusory monsters with greater reality.', class: 'Illusionist' },
  { name: 'Major Creation', level: 5, description: 'Creates larger, longer-lasting objects.', class: 'Illusionist' },
  { name: 'Projected Image', level: 5, description: 'Illusory double delivers spells.', class: 'Illusionist' },
  { name: 'Seeming', level: 5, description: 'Changes appearance of multiple creatures.', class: 'Illusionist' },
  { name: 'Summon Shadow', level: 5, description: 'Summons semi-real shadow creatures.', class: 'Illusionist' },
  { name: 'True Seeing', level: 5, description: 'Reveals things as they truly are.', class: 'Illusionist' },
  { name: 'Veil', level: 5, description: 'Illusion disguises group’s appearance.', class: 'Illusionist' },
  { name: 'Wall of Force', level: 5, description: 'Creates an unbreakable invisible wall.', class: 'Illusionist' },
  { name: 'Mass Suggestion', level: 6, description: 'As suggestion, but affects many.', class: 'Illusionist' },
  { name: 'Permanent Illusion', level: 6, description: 'Creates illusion that lasts until dispelled.', class: 'Illusionist' },
  { name: 'Programmed Illusion', level: 6, description: 'Illusion triggered by conditions.', class: 'Illusionist' },
  { name: 'Shades', level: 6, description: 'Summons powerful semi-real shadow creatures.', class: 'Illusionist' },
  { name: 'True Programmed Image', level: 6, description: 'Complex illusion with triggers and duration.', class: 'Illusionist' },
  { name: 'Vision', level: 6, description: 'Receives divine or mystical vision.', class: 'Illusionist' },
];